// import React from "react";
// import { Portlet, PortletBody } from "../../partials/content/Portlet";
// import FormBuilder from "../../widgets/FormBuilder";


// export default function FormBuilderPage(){

// return(
// <>
// <Portlet className="kt-portlet--height-fluid kt-portlet--border-bottom-brand">
//         <PortletBody heightfluid={true}>
//         <FormBuilder  />
//     </PortletBody>
// </Portlet>
// </>
// );
// }